### ISSUE TITLE
What are the main differences between this and "chunkhang/vim-mbsync"

### ISSUE THREAD

**Issue by simaoafonso-pwt** [Fymyte/mbsync.vim#2]
https://github.com/chunkhang/vim-mbsync

I found this plugin that does the same thing. Any reason why did you not use that one? Does it have any downsides?

**Comment by Fymyte** [comment]
I first did not found this plugin, so I decided to create one myself, but I think there is two benefits for my version:
1. Options which doesn't belong to a section are considered to be an error.
2. An invalid value type after an option is also considered to be an error.
